// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkVzh2C7_iOWE174uxkjJsijYUd7pJ6aw',
    appId: '1:371334703113:web:c270d0054aaa52f09cb0d8',
    messagingSenderId: '371334703113',
    projectId: 'learningfirebase-a4011',
    authDomain: 'learningfirebase-a4011.firebaseapp.com',
    storageBucket: 'learningfirebase-a4011.appspot.com',
    measurementId: 'G-J7R31PX7FM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFl-VKydSKbTR7mxUio8AE2wIzogyt0zE',
    appId: '1:371334703113:android:d92e3d8d018702019cb0d8',
    messagingSenderId: '371334703113',
    projectId: 'learningfirebase-a4011',
    storageBucket: 'learningfirebase-a4011.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDV2MLU7qgtwXZkmX89aED_dQwLvOqZ7IE',
    appId: '1:371334703113:ios:28f189ccc334d4bb9cb0d8',
    messagingSenderId: '371334703113',
    projectId: 'learningfirebase-a4011',
    storageBucket: 'learningfirebase-a4011.appspot.com',
    iosBundleId: 'com.example.ecommerce',
  );
}
